### ISSUE TITLE
[Bugs] Serious Issues with both unofficial and official builds

### ISSUE THREAD

**Issue by Robotia** [TCPR/KCauldron#1]
The version of KCauldron @spannerman79 forked from the prok.pw gitlab does not include many of the fixes which @Prototik made after July 25th.
Whatever changes were not included have prevented this unofficial build from unloading tile-entities properly:
+ TEs get stuck in a seemingly infinite loop...calling their unload methods until the server stops
+ Some TEs are never actually unloaded
+ TEs to be unloaded seem to be duplicated. There were over 4,000,000 tile entities to be unloaded on my server and that did not end well.
+ The server gets stuck and "times out" on removing this large amount of TEs from the list of TEs to remove.

After dealing with these problems for almost a week now, I have reverted to @Prototik's October 25th build. However this has also introduced its own host of issues:
+ Water does not move quite properly as noted in gitlab issue 222 ([here](https://gitlab.prok.pw/KCauldron/KCauldron/issues/222))
+ Excessive amount of time spent in evaluating net.minecraft.world.WorldServer.getPendingBlockUpdates() for saving next-tick data to NBT for unloading chunks in AnvilChunkLoader

At this point I am just hoping that @Prototik will continue his builds in January as is noted on the gitlab.

**Comment by spannerman79** [comment]
> The version of KCauldron @spannerman79 forked from the prok.pw gitlab does not include many of the fixes which @Prototik made after July 25th.

Those changes in place weren't needed as @Prototik introduced multi threaded processing - which many mods don't respond well to.

As I originally stated if you didn't move on from builds 152 server wise you wouldn't have had an issue - obviously you did hence your issues. I stated that on both Yives forum and also in the README.md.  If you didn't read that then that is not my fault.

http://forums.tcpr.ca/discussion/165/testers-needed-unofficial-kcauldron-1566

Read the second paragraph and I'll quote;

*This build is focused on server admins that have kept at 152 builds and have not continued forward as there were changes done that (I assume) changed world/chunk save/loading.*

**Comment by Yive** [comment]
I will try to merge fixes that were added after 152, no promises though since I don't exactly know how the patch stuff works (never worked with Java before).

**Comment by spannerman79** [comment]
A bit pointless - might as well use builds 153+

153 and onwards was the start of multi threading

**Comment by Yive** [comment]
Well I was just going to add small fixes such as the issue 222 fix for example.

**Comment by spannerman79** [comment]
Your free to do what you wish but that fix was only in place to resolve the start of the attempt to multi thread. Look at the parent commit and you'll see.

153+ builds should have been moved into an unstable or experimental tree.

**Comment by spannerman79** [comment]
What wasn't mentioned @Yive was this was more or less a direct copy/paste to @Prototik GitLab, link https://gitlab.prok.pw/KCauldron/KCauldron/issues/263 where it was discussed further before being closed - and no not closed by me either.

**Comment by Robotia** [comment]
The reason I closed them was because you were being so abrasive towards me and I didn't want to continue this conversation with you....
