### ISSUE TITLE
[Proposal] JNI / JNA Integration

### ISSUE THREAD

**Issue by Robotia** [TCPR/KCauldron#14]
I am thinking of changing some methods to be native C/C++ based for performance. 

For instance, on startup, KCauldron could load mods much faster with native reading/writing.

This could be done in two ways:
Java Native Interface (JNI):
* Requires manual, difficult coding (java header files, which are beyond my basic knowledge of C/C++)
* Very system dependent
* Crash logs will be more difficult to understand
* Probably the faster of the two

Java Native Access (JNA):
* Tried and tested, lots of Q&A support
* Not as easily customizable

**Comment by Bogdan-G** [comment]
natives faster speed, but less user friendly.

**Comment by Robotia** [comment]
Good point. My other worry is that few java users actually know natives, so any contributions will likely decrease.

**Comment by Robotia** [comment]
Decided not to do this, closing.
