### ISSUE TITLE
Regaridng the build process

### ISSUE THREAD

**Issue by KasperFranz** [TCPR/KCauldron#16]
I have a question regarding the build process. 

* What is the difference between the [name].jar and [name]-server.jar? 
* The libraries there are required for it to run are the bin folder in bunde (which I have to put in the same folder and rename to libraries) - yes?

as far as i can see they are pretty close to each other in general (size wise)

**Comment by Robotia** [comment]
The server jar is actually for the server. I'm not sure what the other jar is for.

You can download a bundle with the libraries at https://accretion.us/development

**Comment by KasperFranz** [comment]
that isn't really helpful ;)

the bundle you made (and where on the site is it?) where did you get that from?

**Comment by Robotia** [comment]
I'm not sure, I had them from an old cauldron server I used to run.

**Comment by MixSt** [comment]
Good day, dear @Robotia! I tried to use your unofficial build of TCPR KCauldron on my public servers, it's pretty! BUT! I want to know diffirence between your build and TCPR build!

**Comment by Robotia** [comment]
@MixSt Right now, the only big difference between this TCPR build and the ones on https://accretion.us/development is that the latter places a limit on the speed of Redstone repeaters to prevent extremely fast timers from working. 

However, this TCPR build is basically a continuation of my builds with some optimizations. I suggest you download it.

**Comment by KasperFranz** [comment]
I got a problem regarding the fake network handler acting up with crashes again (the ones which should have a fix in this build) 

https://gist.github.com/KasperFranz/cab78b3916dc38095a09

which should be fixed in this: https://gitlab.prok.pw/KCauldron/KCauldron/issues/268
