### ISSUE TITLE
Crash with enderIO

### ISSUE THREAD

**Issue by KasperFranz** [TCPR/KCauldron#17]
I got a problem regarding the fake network handler acting up with crashes again (the ones which should have a fix in this build)

https://gist.github.com/KasperFranz/cab78b3916dc38095a09

which should be fixed in this: https://gitlab.prok.pw/KCauldron/KCauldron/issues/268

**Comment by Robotia** [comment]
@KasperFranz Are you using the jar in bin/ or in the root folder?

**Comment by KasperFranz** [comment]
I used the release from here and the libraries from a earlier build (it started without problems) 

Den 22/01/2016 8.13 PM skrev Sam <notifications@github.com>:

@KasperFranz Are you using the jar in bin/ or in the root folder?

**Comment by Robotia** [comment]
@KasperFranz Please use the libraries from this build so we can make sure this error isn't library-related. 
Also, did you encounter this error with official KCauldron? I don't think that commit would've solved this problem.

**Comment by KasperFranz** [comment]
It works in the kcauldron 174 build

**Comment by KasperFranz** [comment]
This is fixed in the latest pr. 
But introducing another crash (making another issue)
