### ISSUE TITLE
Server not starting up, missing Joptsimple

### ISSUE THREAD

**Issue by DavidDiack** [TCPR/KCauldron#18]
Regular cauldron from https://gitlab.prok.pw/KCauldron works fine, but I want to use this one because of the TickNextTick issue. It won't start up for some reason:

Exception in thread "main" java.lang.NoClassDefFoundError: joptsimple/OptionSpec
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Unknown Source)

**Comment by Bogdan-G** [comment]
@DavidDiack set the official version of the 175, and then the substitution of files here.

**Comment by Robotia** [comment]
@Bogdan-G It is a libraries issue, I should've uploaded the entire ZIP as a release. Going to do that in a minute.

**Comment by Robotia** [comment]
@DavidDiack See the releases again, I have uploaded the proper server setup.

**Comment by Yive** [comment]
You only uploaded the jar file @Robotia I'll be uploading Build 2 onto the mirror in a couple of minutes, just need to setup the webpage for it. I'll be building it on Java 8 so hopefully that doesn't cause any problems, but I think most people are probably on Java 8 by now anyways.

**Comment by Robotia** [comment]
@Yive I meant that I had uploaded it in release 1 earlier. I forgot to put it in release 2 again ;)

**Comment by Yive** [comment]
oh oops, didn't realise that :laughing: I'll still upload only 175.2 since it seems to be more stable.

**Comment by Robotia** [comment]
@Yive Ok. Also, placing the release 2 jar into the server bundle from release 1 should work fine. I don't think it works if you use the bundle that's already on TCPR, which is why @DavidDiack was having this problem.

**Comment by Yive** [comment]
You mean using bin instead of libraries?

**Comment by Robotia** [comment]
@Yive The jar is in the main folder of the zip instead of being under bin. The libraries in the bundle from release 1 are slightly different.

**Comment by Yive** [comment]
oh okay then, I'll test out & see what works before uploading then.
