### ISSUE TITLE
Crash - java.lang.ClassCastException

### ISSUE THREAD

**Issue by KasperFranz** [TCPR/KCauldron#19]
We are having this crash after updating to the latest pr 
https://gist.github.com/KasperFranz/1dd9be15bbb4839a9b63

It seks to be with te New way chunks is processed

**Comment by Robotia** [comment]
@KasperFranz I am having this same problem with the Remain in Motion mod, I'm going to be reverting the change soon.

**Comment by Robotia** [comment]
@KasperFranz See Release 3.
