### ISSUE TITLE
KC server freezes on dimension load

### ISSUE THREAD

**Issue by Mickimoo2** [TCPR/KCauldron#20]
Basically what the title says, it occurs both with 1388 and 1448

Full Log: http://paste.feed-the-beast.com/view/9b345244

Final lines of console:
[00:25:40 INFO]: Loading dimension 0 (world) (net.minecraft.server.dedicated.DedicatedServer@441dd38e)
[00:25:40 INFO]: Loading dimension -100 (DIM-100) (net.minecraft.server.dedicated.DedicatedServer@441dd38e)

**Comment by Robotia** [comment]
@Mickimoo2 What is `RemoteIO`? 

And are you using coremods...

**Comment by Robotia** [comment]
@Mickimoo2 Similar to [this](http://www.minecraftforum.net/forums/support/modded-client-support/2305968-forge-crash). Do you have OpenBlocksLib?

**Comment by Mickimoo2** [comment]
@Robotia I do have OpenModsLib not OpenBlocksLib

**Comment by Robotia** [comment]
@Mickimoo2 What version of KCauldron are you using?

**Comment by Mickimoo2** [comment]
Yive gave me this link about a week ago:
 http://i.tcpr.ca/KCauldron-1.7.10-1448.UNOFFICIAL.zip
And the 1388 version was custom coded as it was a fork of prototiks build.

**Comment by Robotia** [comment]
@Mickimoo2 Please see the latest build we have [here](https://github.com/TCPR/KCauldron/releases).

**Comment by Mickimoo2** [comment]
Can't, it needs to be a 10.13.4 forge build. Otherwise its too new

**Comment by Robotia** [comment]
@Mickimoo2 Then I am sorry, I cannot help you. You will need to post your issue on the official KCauldron site [here](https://gitlab.prok.pw/KCauldron/KCauldron/issues).
