### ISSUE TITLE
"Crash" - java.lang.NullPointerException: Ticking entity

### ISSUE THREAD

**Issue by KasperFranz** [TCPR/KCauldron#24]
We are getting this "crash" in the logs (it isn't crashing)

https://gist.github.com/KasperFranz/a2a38d2515443576de46

**Comment by KasperFranz** [comment]
This is a issue there seems to be related
https://gist.github.com/KasperFranz/40fc17a73f472b124a4d

**Comment by Robotia** [comment]
@KasperFranz disable power Crystal nether ores explosions as a temporary fix, I will look into this.

**Comment by KasperFranz** [comment]
That is done
for anyone else it's 

    # NetherOres have a chance to explode when mined if true.
    B:ExplosionEnable=false


in config/powercrystals/netherores/common.cfg

Can't wait to see how it all goes with this updated version :) :+1:

**Comment by Robotia** [comment]
@KasperFranz See release 4.

**Comment by KasperFranz** [comment]
Possible to add a file to the release with only the jar and libraries :)?
since some of us use symlinks to make it faster to deploy

**Comment by KasperFranz** [comment]
It didn't fix the issue sadly.

https://gist.github.com/KasperFranz/95569816e3de725476b5

**Comment by Robotia** [comment]
@KasperFranz See Release 5.

**Comment by KasperFranz** [comment]
Sadly it still seems to crash using release 5 :/ https://gist.github.com/KasperFranz/fd26e7ab4fc91bd125c4

**Comment by enterprise12nx** [comment]
Same

**Comment by KasperFranz** [comment]
@Robotia  can you reopen this issue until it is resolved :)?

**Comment by Robotia** [comment]
@KasperFranz This should *finally actually* fix it :smiley: 
I had left the assertion error you had added in the pull request, meant to leave it removed as `else { return null; }`.

**Comment by KasperFranz** [comment]
oh lets try it :D should be able to test this later today (in some hours)

**Comment by Robotia** [comment]
@KasperFranz see build 6.

**Comment by KasperFranz** [comment]
That fixed that issue :+1:
