### ISSUE TITLE
Better Shops Plugin

### ISSUE THREAD

**Issue by Cracks777** [TCPR/KCauldron#25]
is there any way to make this work with Better Shops Bukkit Plugin?

**Comment by KasperFranz** [comment]
I think you should provide the crash you get :)

**Comment by Robotia** [comment]
@Cracks777 
What @KasperFranz said.

**Comment by Cracks777** [comment]
it doesnt crash, you just cant riclk to open a shop.

**Comment by Cracks777** [comment]
https://gitlab.prok.pw/KCauldron/KCauldron/issues/138

**Comment by Cracks777** [comment]
https://github.com/moomaxie/BetterShops/issues/10

**Comment by Robotia** [comment]
@Cracks777 This will require some debugging to figure out, I will talk with moomaxie.

**Comment by Cracks777** [comment]
Ok Thanks For looking into this.

**Comment by Robotia** [comment]
@Cracks777 I have heard nothing back from @moomaxie, it seems he/she is inactive. There is nothing I can do right now about this, I am sorry.

**Comment by Cracks777** [comment]
That is fine. i want to say back in the day it did work with cauldron, i swear i used to before and all i have ever used is cauldron. mabie if i can find a version that it works with then we can find what was changed?

**Comment by Time6628** [comment]
Try out GlobalMarket 2. The server listings function works great :smile_cat:

**Comment by Robotia** [comment]
@Cracks777 See https://github.com/Robotia/BetterShops/releases

**Comment by Cracks777** [comment]
Thank You so Much Testing now. :p

**Comment by Cracks777** [comment]
Sorry to have to say but it still will not open the shop on click? its not throwing out any errors now but wont do anything either?

**Comment by Cracks777** [comment]
Update: The shop does not open on click if you use the chest/sign, but if you type /bs open {shopname here} and chande it to a npc shop and save it then you can click on the npc and it will open. hope you understand what im talking about. If you need more info pleas ask.

**Comment by Cracks777** [comment]
So it has a workaround.

**Comment by Robotia** [comment]
@Cracks777 Try this: https://github.com/Robotia/BetterShops/releases/tag/2.1.3-unofficial-2.test

**Comment by Cracks777** [comment]
OK THANK YOU.

**Comment by Cracks777** [comment]
no luck buddy. but thanks for trying.

**Comment by Robotia** [comment]
Since this has been determined to be a BetterShops-specific issue, reposting it on the BetterShops fork.
