### ISSUE TITLE
Entities without players nearby, but chunk loaded

### ISSUE THREAD

**Issue by Mortal42** [TCPR/KCauldron#28]
KCauldron appears to have an interesting behavior with chunk loading, entities, and not having a player nearby.
What I've found is that chunk loading works fine for tile entities (when skip tile entities is false). Machines continue to work, etc.
But if I set up a chicken spawner, I see from logs that the chickens are spawning, but once they've spawned they do not move. Teleporting back to the location shows them all clumped together for  a moment before they begin to float down and die from some spikes.
Items appear to behave similarly to monsters. If I set up a dispenser to drop something, the item doesn't move until I return to the chunk. These items do appear to get cleaned up from the item timeout though.

I've tried changing the entity activation range to 0 but it had no effect.

The mod list I have is fairly minimal: thermal expansion/dynamics for testing to see if the items would get picked up from a distance. Extra utilities for picking up the items. OpenBlocks for trying to move monsters with fans. Then NEI, journeymap, and I've tried both FTB Utilities for chunk loading and serversidechunkloader, both acting the same.

Is this expected behavior, or is there a setting I have not found yet?

**Comment by Robotia** [comment]
@Mortal42 
It is a setting. 
**Having an activation range of 0 means those entities would *never* do anything.**

**Comment by Mortal42** [comment]
To note, I've tried the default setting, as well as changing the activation ranges to both 0 and 320000, no change in behavior of the chickens in any case.

**Comment by Mortal42** [comment]
Here's a video demoing it, though I added ender storage to be able to demonstrate it easier.
https://youtu.be/LnTWSCTdG2c

It seems that once I go further than 8 chunks away from the loaded chunk, the items continue to spawn as shown in the terminal at the bottom right of the video, but they stop falling, and so they don't get in range of the transfer node below them that picks them up and sticks them in the ender chest.

At the end of the video you can see this when I teleport back to the chunk and a bunch of them fall suddenly.

**Comment by Robotia** [comment]
Have you tried setting the activation range to -1 ?

**Comment by Mortal42** [comment]
Just tried without any change to the behavior.
    entity-activation-range:
      animals: -1
      monsters: -1
      misc: -1

Same behavior once I move >8 chunks away.

**Comment by Cracks777** [comment]
@Mortal42 what is your entire mod list?

**Comment by Mortal42** [comment]
Below is the list. Note that FTBUtilities is disabled currently as I was testing ServerSideChunkLoader in case it was due to the chunk loading mod.


mods/OpenModsLib-1.7.10-0.9.jar
mods/ThermalFoundation-[1.7.10]1.2.1-110.jar
mods/1.7.10/CodeChickenLib-1.7.10-1.1.3.138-universal.jar
mods/FTBLib-1.7.10-1.0.15.jar.disabled
mods/extrautilities-1.2.12.jar
mods/journeymap-1.7.10-5.1.3-unlimited.jar
mods/FTBUtilities-1.7.10-1.0.15.1.jar.disabled
mods/ThermalExpansion-[1.7.10]4.1.0B1-235.jar
mods/CoFHCore-[1.7.10]3.1.0B1-322.jar
mods/ThermalDynamics-[1.7.10]1.1.0-161.jar
mods/CodeChickenCore-1.7.10-1.0.7.47-universal.jar
mods/NotEnoughItems-1.7.10-1.0.5.118-universal.jar
mods/ServerSideChunkLoader-0.2.5.jar
mods/EnderStorage-1.7.10-1.4.7.37-universal.jar
mods/OpenBlocks-1.7.10-1.5.jar

**Comment by Cracks777** [comment]
mods/ServerSideChunkLoader-0.2.5.jar

replace this with chicken chunks and see if it still happens.

**Comment by Robotia** [comment]
I agree, ChickenChunks links in with CodeChickenCore. It would be a good replacement. Let me know if this works for you.

**Comment by Robotia** [comment]
@Mortal42 Also, are you using our unofficial KCauldron builds?

**Comment by Mortal42** [comment]
Stuck in ChickenChunks-1.7.10-1.3.4.19-universal.jar

Without any chunk loader in the chunk, I noticed the console was still spawning sandstone.
Added a chicken chunks spot loader to load just the one chunk, same behavior as before with items not moving.

Added a normal Chicken chunks Chunk Loader. If set to radius 1 or 2 (1 chunk and 9 chunks respectively), it does not work. If I increase the radius to 3, for 25 chunks total, it begins to work. I recall reading something somewhere (in relation to cauldron/mcpc/spigot/etc) about chunks not activating unless they are surrounded by loaded chunks, but given that a radius of 2 didn't work that seems odd.

Given this behavior, I re-enabled FTB Utilities and set a 5x5 area of chunks around the item spawner as chunk loaded. This also works and the ender chest continues to receive the items. If I lower this down to a 3x3 area around the item spawner, it stops working.

**Comment by Cracks777** [comment]
@Mortal42  Also,  EnderStorage is at 1.4.7.38 for the latest version. Not sure if this is any major changes.

**Comment by Cracks777** [comment]
Stuck in ChickenChunks-1.7.10-1.3.4.19-universal.jar? whats that mean.

**Comment by Mortal42** [comment]
I am using the latest version from this github, self built. I've also tried the unofficial release v3 as well as the official builds.

I also saw this behavior without ender storage, I added that just as an easier way to test and show it in a video.

**Comment by Mortal42** [comment]
@Cracks777 That was in suggestion to @Robotia asking me to try Chicken Chunks for chunk loading.

**Comment by Cracks777** [comment]
http://chickenbones.net/Pages/links.html for the latest

**Comment by Robotia** [comment]
@Mortal42 As a temporary solution, you might be able to hide an NPC named "?" somewhere around there. Since it is essentially an EntityPlayer, it should solve your problem.

**Comment by Mortal42** [comment]
@Cracks777 the chunk loading behavior appears to be the same regardless of what chunk loading solution I use. If I load a large amount of chunks around the area, it works. If I load a single chunk, it does not.

Also, chicken chunks 1.3.4.19 is the latest version listed on that page for 1.7.10. And 1.0.7.47 is the latest version of code chicken core for 1.7.10.

@Robotia I tried spawning a villager and naming it "?", this did not work. Do you specifically mean an NPC from a plugin, or any named NPC?

**Comment by Robotia** [comment]
@Mortal42 A player NPC, from CitizensNPC. See [here](https://github.com/TCPR/Fixes/tree/master/Citizens-Cauldron-Fix).

**Comment by Mortal42** [comment]
@Robotia I installed citizens, used /npc create ?
This created a Steve standing still, but it did not fix the issue... if I move away, the issue persists. It doesn't look like the NPCs I spawned are keeping the area loaded like a real player does.

**Comment by Robotia** [comment]
@Mortal42 `/npc create Notch`, `/npc look`, `/npc path` edit the path to make it move around a bit.
More help is on the Ciitzens wiki [here](http://wiki.citizensnpcs.co/Citizens_Wiki).

**Comment by Mortal42** [comment]
@Robotia That appears to have done the job and can work as a temporary solution. I'd be happy to help with trying to solve the actual problem with chunk loaders, if it is expected to work anyway. I'm a bit surprised I've never seen issues with chunk loading and kcauldron not mentioned before. My java is a bit rusty, though.

**Comment by Robotia** [comment]
@Mortal42 Awesome, glad I could help! Most servers don't have setups where systems need to run while no one is present, that's probably why it hasn't been mentioned.

**Comment by Mortal42** [comment]
@Robotia Yeah, most servers that do likely use base forge. Kcauldron is just so much faster than base forge though, which is why I've been using it myself for running FTB Infinity.

There've only been two issues I've found so far, one being the chunk loading, and the other being super minor bug when dropping single items from a stack using the mouse. Hard to explain what I mean, but it's also extremely minor.

**Comment by Mortal42** [comment]
Talked briefly with @Robotia outside of here. Closing as there are at least two workarounds, and it's unlikely to be looked into any time soon. Potential workarounds: Load a lot more chunks around the area, or use an NPC from Citizen to act as a player.

**Comment by Eufranio** [comment]
Still not loading.
