### ISSUE TITLE
Nether ore Armed Ore Crash (Explosion)

### ISSUE THREAD

**Issue by enterprise12nx** [TCPR/KCauldron#29]
Using the latest fix, Nether ore explosions cause the server to crash(Armed Ores)

Im using world border to generate my world

Im on my phone so i could only upload them in zip files, hope thats ok!
[latest.zip](https://github.com/TCPR/KCauldron/files/105075/latest.zip)
[fml-server-latest.zip](https://github.com/TCPR/KCauldron/files/105077/fml-server-latest.zip)

**Comment by Robotia** [comment]
@enterprise12nx See build 6.
