### ISSUE TITLE
Biomes o plenty Already Decorating! worldborder Task Exception

### ISSUE THREAD

**Issue by enterprise12nx** [TCPR/KCauldron#30]
Will try the nether ores fix when home, but now there is also a problem with Biomes o Plenty i wasnt having using 1614.175 

It throws an Already Decorating! error which causes worldborder to throw an exception too

[fml-server-latest.zip](https://github.com/TCPR/KCauldron/files/105200/fml-server-latest.zip)
[latest.zip](https://github.com/TCPR/KCauldron/files/105201/latest.zip)

**Comment by Robotia** [comment]
@enterprise12nx Does this happen only with the unofficial builds?

**Comment by enterprise12nx** [comment]
Im not 100% sure, i had to make a new world due to removing reikas horrible mods(never would have added them if i knew they caused so many problems, had to delete all config files for my modpack and such)

I had been using 1614.175(dont believe thats unofficial) but we got the out of sync errors between dimensions, so i used Package #3 here, which fixed that,  but now worldgen has been a mess, worldborder constantly stops, massivecore for factions is throwing an error about a player inventory? 
Im using #5 rn, but im not home yet to test another build yet, when im home i will try build 1614.175 again and report back if it still happens

**Comment by Robotia** [comment]
@enterprise12nx I looked through the code and realized I made a serious error, I think I have resolved that. Revising build 6 before anyone downloads it.

**Comment by enterprise12nx** [comment]
Haha sweet, its all good.  I just started learning coding in college as its my major and i dont even realize when i make mistakes 😂

**Comment by Robotia** [comment]
@enterprise12nx Yea I forgot to add a little bit that dealt with chunk generation, world would keep trying to regen chunks that were already generated. Should be fixed by 36a673d838e324bb850faafe4a0545c9d166e45a

See build 7.

Close this issue if it works :smile:

**Comment by enterprise12nx** [comment]
Alright im home in 2 hours to test

**Comment by enterprise12nx** [comment]
Testing it now, had a few questions for the configs i never understood.
in cauldron.yml 
what exactly do these settings mean, should i change any for a heavily modded dedicated server?
  load-chunk-on-forge-tick: false
  check-entity-max-speeds: false
  chunk-gc-grace-period: 0
  check-entity-bounding-boxes: true
  load-chunk-on-request: true
  entity-bounding-box-max-size: 1000
  dump-materials: false

fake players do login:
Im aware of them, but what does this do to them?

**Comment by enterprise12nx** [comment]
Fixed, ty

**Comment by Robotia** [comment]
@enterprise12nx 
+ load-chunk-on-forge-tick: loads a chunk if something within it is accessed by Forge (difficult to explain, but it's good to enable if someone complains about teleport pipes from BuildCraft not working)
+ check-entity-max-speeds: limits entity speed
+ chunk-gc-grace-period: minimum time in milliseconds a chunk in the queue to be unloaded must go unaccessed before it is unloaded
+ bounding-boxes: prevents massive entities (bigger than zombie giants, /spawnmob giant from Essentials to see a giant)
+ load-chunk-on-request: load a chunk when a mod asks for it to be loaded
+ bounding-box: maximum entity size
+ dump-materials: I think this deals with the FML GameRegister for block/item IDs
+ fake-players-do-login: When a forge mod creates a `FakePlayer` for block breaking checks, enabling this means the server will create a login event when a fakeplayer is used.
