### ISSUE TITLE
[Proposal] KC-Unofficial Metrics

### ISSUE THREAD

**Issue by Robotia** [TCPR/KCauldron#33]
I'd like to set up metrics to get an idea of how many servers use these builds. If I hear no objections, I will start looking into how to set this up.

**Comment by Cracks777** [comment]
Good Idea! I'd like to see how many people use this.

**Comment by KasperFranz** [comment]
It should be possible to implement something like this patch

https://github.com/PaperSpigot/Paper/blob/master/CraftBukkit-Patches/0015-Metrics.patch

Just change the line 229 (https://github.com/PaperSpigot/Paper/blob/master/CraftBukkit-Patches/0015-Metrics.patch#L229) to be KC-Unofficial :)

I should be able to make a pull request for that when i get home tonight :)

**Comment by Yive** [comment]
+1

but this should only happen after a rename imo.

**Comment by Cracks777** [comment]
rename this DO IT

**Comment by iKaneki-Ken** [comment]
Why not ditch the Cauldron name altogether?

**Comment by Yive** [comment]
We were going to do that, I suggested Dropper mainly since it's already in minecraft, but not sure what it'll switch to as of yet.

**Comment by spannerman79** [comment]
Just be careful - I had to actually make the change [here](https://github.com/TCPR/KCauldron/blob/d74bae22448c0a1c2d0d61ec7bbf9074549b04b4/src/main/java/org/bukkit/craftbukkit/CraftServer.java#L143) to get some backwards compatibility with older plugins and some other mods as they expected Cauldron - not KCauldron - in the server name.  Changing it to Dropper *may* have some side effects.

For the argument that "plugins and mods shouldn't use `serverName` for detection" - I agree - but some do.  You won't get those plugins to update *just* for 1.7.10 as the vast majority have moved onto 1.8 and even fully away from BukkitAPI and onto SpongeAPI

**Comment by Robotia** [comment]
@spannerman79 Good point.

We might be able to just create another string var instead.

**Comment by Yive** [comment]
Do you know of any plugins / mods that do this, @spannerman79 Just so that we could maybe figure out a way to keep those plugins / mods working after renaming this project.

**Comment by spannerman79** [comment]
Not off hand.  I don't even have logs of the errors going back before the 3rd Dec anymore (before https://github.com/TCPR/KCauldron/commit/d74bae22448c0a1c2d0d61ec7bbf9074549b04b4 was made) or I could just give a logfile dump of before/after.

**Comment by iKaneki-Ken** [comment]
@Yive This plugin when installed on a (K)Cauldron based server looks for the server wrapper name.

---

http://dev.bukkit.org/bukkit-plugins/scoreboardstats/
