### ISSUE TITLE
My Server doesn't start up and KCauldren or Minetweaker seems to be the problem

### ISSUE THREAD

**Issue by Mellow1000** [TCPR/KCauldron#34]
I have a crundee craft server and tried updating it because of the new update but everytime I run the server I get this error. http://pastebin.com/jRUxUUcT
Minetweaker seems to be the problem but when I disable it, it doesn't seem to work.
I posted this on KCauldron and Minetweaker but Idk which forum is better so I did on both

**Comment by Cracks777** [comment]
UE  MineTweaker3{3.0.9B} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.9C.jar)

U=Unloaded
E=Errored

Remove minetweaker and try to start, if it starts thats the problem.

**Comment by Mellow1000** [comment]
That does not work as mod start not working

**Comment by Robotia** [comment]
One of your mods is injecting java bytecode into the modified World class. It's Mobius Core, get rid of it.

**Comment by Mellow1000** [comment]
Fixed, Thanks

**Comment by KookosPahkina** [comment]
I shall correct here as i was the one fixing the server because it was my server, that i was using KCauldron and forgot to add their mobiuscore fix to the mods

**Comment by Mellow1000** [comment]
Yes he was, I was just the one posting the forum

**Comment by Robotia** [comment]
Closing this issue I guess.
