### ISSUE TITLE
[PaperSpigot Patch] Don't create region to check if it's there

### ISSUE THREAD

**Issue by iKaneki-Ken** [TCPR/KCauldron#36]
Sorry, new to how Github works, tried to PR, but couldn't.

---

http://pastebin.com/sUAyMjPF

**Comment by Robotia** [comment]
Sorry, I just made this fix in https://github.com/TCPR/KCauldron/commit/9fc6cf3770a352e4f66f64270bee13dfce473db0 :cry: . Thank you though!
