### ISSUE TITLE
[Crash] - Kcauldron[v.8] - Chunkgen nullpointer

### ISSUE THREAD

**Issue by KasperFranz** [TCPR/KCauldron#37]
Seems to have a problem in the chunk generation (Exception in server tick loop)

I sadly can't say what happened or at why it happened

Crash report: https://gist.github.com/KasperFranz/0f07ab97f40720689a66

**Comment by Robotia** [comment]
Very strange...
I looked at the code, it's not world generation. Turns out that a loaded chunk was null. :confused:

**Comment by Bogdan-G** [comment]
Well, sometimes the server writes that some part in the loaded chunk null
