### ISSUE TITLE
Redstone Issue 1614.175.UNOFFICIAL.8

### ISSUE THREAD

**Issue by xJonL** [TCPR/KCauldron#40]
Redstone having some issues activating and what not~
https://files.xjon.me/Bnf8A.mp4

**Comment by Robotia** [comment]
@xJonL Was probably because I added Redstone speed limiters. I can add a config setting where this is disabled by default.

**Comment by xJonL** [comment]
@Robotia Okay, thank you sweetie.

**Comment by Yive** [comment]
Not sure if related, but machines lose power randomly after switching to KC-Unofficial.

**Comment by Robotia** [comment]
@Yive Yes definitely related, fixing this as we speak.

**Comment by Robotia** [comment]
@Yive @xJonL See release build 9.
