### ISSUE TITLE
Already Decorating!! Unknown net.minecraftforge.common.chunkio.QueuedChunk

### ISSUE THREAD

**Issue by enterprise12nx** [TCPR/KCauldron#44]
http://pastebin.com/71w7bW85

This is the error, i just took it out of fml.latest.log turns out its still happening in 1614.176 but maybe happens less often.

**Comment by Robotia** [comment]
@enterprise12nx Looks like biomes o' plenty is your culprit :cry: I will see if I can find the cause. Is it possible to test this on Vanilla Forge?

**Comment by enterprise12nx** [comment]
well it wasnt happening when i was using 1614.175 or i think even unoffical #3 but i removed reikas mods and regenerated all my configs, and then it started happening, idk if its a setting or some conflict

**Comment by Robotia** [comment]
@enterprise12nx Neither of those things should've changed it :confused:. There wasn't really any difference between 175 and 176. I think it's a world gen problem.

**Comment by enterprise12nx** [comment]
Any idea how i can fix it?

**Comment by Robotia** [comment]
For now, I suggest that you let it persist, since you're just pre-gening the server.

**Comment by enterprise12nx** [comment]
Well i think its messing worldgen up, because we found a river from the streams mod, and it was all cobble, the others are water though

**Comment by Robotia** [comment]
@enterprise12nx Wait...I think that's related to 7bf14b4f378fb7afd7071b2751ef455e3c6fdab2. If you see recurrent cobblestone rivers, let me know ASAP.

**Comment by enterprise12nx** [comment]
@Robotia ok, i'll keep an eye out, we havent ventured out to far, but have seen one so far

**Comment by Robotia** [comment]
@enterprise12nx Will release this fix with build 10. Or, you can build it yourself :smile:

**Comment by enterprise12nx** [comment]
The already decorating error? Or the cobble rivers 😂

**Comment by Robotia** [comment]
@enterprise12nx The already decorating error. Not sure what's up with the cobblestone rivers, might be on our end. Let me know if you see another one.

**Comment by enterprise12nx** [comment]
Ok, awesome i think that should fix our crashes.  I will regen the chunks with the cobble river and watch for others

**Comment by enterprise12nx** [comment]
@Robotia testing out build 11

**Comment by Robotia** [comment]
@enterprise12nx Sounds good.

**Comment by Shybella** [comment]
http://prntscr.com/9wn5nk

**Comment by Robotia** [comment]
Yes, this is a new problem now, sorry about that. I will be reverting it soon, it looks like CoFHCore is at fault. I had the same issue earlier today.

**Comment by Cracks777** [comment]
has this been reverted yet?
if so it is still doing this in build 12

**Comment by Robotia** [comment]
@enterprise12nx It has been reverted, but not in a release yet, only in the code. :confused:

**Comment by Cracks777** [comment]
yes i seen so i deleted my comment. that you tho, also is there goning to be a fix for the original issue?

**Comment by Robotia** [comment]
@Cracks777 Not sure yet, I am considering making a timed task so if the chunk's generation times out, it'll just cancel itself.

**Comment by Cracks777** [comment]
ok, and again thanks for you had work :)

**Comment by Robotia** [comment]
Sure.

**Comment by Cracks777** [comment]
why are the chunk's generation timeing out? it wasnt before?

**Comment by Robotia** [comment]
@Cracks777 It's an issue with my new release, sorry about this. Turns out that chunk-gen hangs because of liquids...at least I know that now :smile:
You can download the fixed version [here](https://accretion.us/repo/development/KCauldron/kcal12_5.jar)

**Comment by Cracks777** [comment]
using that build the server still timesout and it starts throwing errors so fast the log is thousands of lines in seconds?

**Comment by Cracks777** [comment]
_a(Chunk.java:710) [apx.class:?]
	at net.minecraft.world.World.func_147465_d(World.java:813) [ahb.class:?]
	at net.minecraft.block.BlockDynamicLiquid.func_149813_h(BlockDynamicLiquid.java:227) [akr.class:?]
	at net.minecraft.block.BlockDynamicLiquid.func_149674_a(BlockDynamicLiquid.java:159) [akr.class:?]
	at net.minecraft.world.WorldServer.func_147454_a(WorldServer.java:616) [mt.class:?]
	at net.minecraft.world.WorldServer.func_147464_a(WorldServer.java:593) [mt.class:?]
	at net.minecraft.block.BlockDynamicLiquid.func_149726_b(BlockDynamicLiquid.java:389) [akr.class:?]
	at cofh.asmhooks.block.BlockTickingWater.func_149726_b(BlockTickingWater.java:19) [BlockTickingWater.class:?]
	at net.minecraft.world.chunk.Chunk.func_150807

**Comment by Robotia** [comment]
@Cracks777 Are you certain? Please give a full several lines of the log, 100 lines should be good. I am in the process of trying to fix it, I've been using that build on my server and haven't had problems with it.

**Comment by Cracks777** [comment]
teleport to a random location that you know theres no chunks generated yet, then you will get all kinds of spam and then it will timeout the clients.

**Comment by Cracks777** [comment]
like i teleported to -50000 90 -2000 and its froze.

**Comment by enterprise12nx** [comment]
@Robotia Already Decorating Error is here, but slightly different, seems to happen less often.
http://pastebin.com/eWAunxCw
