### ISSUE TITLE
[Crash] - Kcauldron[v.10] - java.lang.AbstractMethodError

### ISSUE THREAD

**Issue by KasperFranz** [TCPR/KCauldron#46]
There seems to be a problem with the v10 regarding to the chunkprovider server (crahed on startup)

Crash report: https://gist.github.com/KasperFranz/9785b95c551850031948

**Comment by Robotia** [comment]
@KasperFranz Thanks, just got it, will release hotfix asap.

**Comment by KasperFranz** [comment]
Still crashing 
https://gist.github.com/KasperFranz/d299caa905c282e6c566

**Comment by Robotia** [comment]
@KasperFranz Think I should finally have it...I used an `Exception e` instead of `Error e`. `AbstractionError` is not something I'm used to :confused:  sorry
