### ISSUE TITLE
Improper type detected for entity list in world #. Regenerating tracking list.

### ISSUE THREAD

**Issue by enterprise12nx** [TCPR/KCauldron#47]
Seeing this spam in console now? not sure what it is

**Comment by enterprise12nx** [comment]
still getting this error from jobs reborn plugin
http://pastebin.com/yCrLqVB0

It spams constantly

**Comment by Robotia** [comment]
@enterprise12nx Please share the improper type detected pastebin log.

**Comment by enterprise12nx** [comment]
whats that @Robotia ?
Also opis is now throwing errors, im using the patched mobious core too

http://pastebin.com/R5LFtv7T

**Comment by Robotia** [comment]
@enterprise12nx If opis is a profiler, get rid of it, it is not useful with KC. Use warmroast instead.

**Comment by Robotia** [comment]
@enterprise12nx The pastebin log for the name of this issue is what I meant.

**Comment by Robotia** [comment]
@enterprise12nx Were you using Build 9 earlier?

**Comment by enterprise12nx** [comment]
i was yes, im using build 11 now,
it was a single line, they dont appear to be happening right now, if i see more

**Comment by Robotia** [comment]
Related to fdd4959dd2d75cf56d2be4e2d68ce81c39888eef. Going to revert it.

WarmRoast won't be able to run there I am sorry, I'll just revert most of the changes then. :confused:

**Comment by Robotia** [comment]
Fixed in build 12

**Comment by Robotia** [comment]
@enterprise12nx
