### ISSUE TITLE
[problem] Kcauldron[v.11] - Problem going from nether to overworld

### ISSUE THREAD

**Issue by KasperFranz** [TCPR/KCauldron#48]
It seems if you go from the nether to the overworld (with eg. a spawn command).

You can't send chat messages, after relogging it throws an internal server error (https://gist.github.com/KasperFranz/9785b95c551850031948) after logging in again you end up at another place (my guess is the location is tied to what your location was in the nether), buit with a "fakeplayer/npc" at "spawn".

**Comment by Robotia** [comment]
@KasperFranz fixed in build 12.

**Comment by enterprise12nx** [comment]
@Robotia so far v12 is most stable, no hard crashes at least, im sure theres improvements to be made though, just glad hard crashes are gone!
