### ISSUE TITLE
Last KCauldron version error

### ISSUE THREAD

**Issue by Esctogrillo** [TCPR/KCauldron#50]
I start my server and all works fine, but in some moment this message flood all the console: 

[KC-Unofficial] Already Decorating a Chunk! Waiting...

This is the complete log (Pt-BR server): 
[fml-server-3.log.txt](https://github.com/TCPR/KCauldron/files/110962/fml-server-3.log.txt)

(With BetterShops error too)

**Comment by enterprise12nx** [comment]
Already Decorating Failure - http://pastebin.com/AJtc9B4t

java.lang.NullPointerException - codechicken.lib.world.World - http://pastebin.com/5L1PnvVU

**Comment by Robotia** [comment]
@enterprise12nx I have a Patreon, it is https://www.patreon.com/robotia

**Comment by enterprise12nx** [comment]
i donated on https://gitlab.prok.pw/groups/KCauldron
not sure who that goes to or how its distributed, but i will donate here occasionally, i just quite my job as im focusing on school (learning java in eclipse rn) but i'll donate sometimes

**Comment by Robotia** [comment]
@enterprise12nx :smile: Thank you, and Java is good to learn in the beginning.

**Comment by enterprise12nx** [comment]
@Robotia np, doesnt minecraft and all this use java?

**Comment by Robotia** [comment]
@enterprise12nx yup

**Comment by Robotia** [comment]
Fixed in build 13.

**Comment by enterprise12nx** [comment]
Testing build 13 @Robotia
