### ISSUE TITLE
[problem] Kcauldron[v.12] - Machines stops working after some time

### ISSUE THREAD

**Issue by KasperFranz** [TCPR/KCauldron#51]
We are experiancing issues where machines stops working after ~20 minutes of uptime.

The issue doesn't seem to exist in the official builds.

I can't pinpoint what should cause it or if it is in chunks or somewhere else.

Special mods:
tickprofiler

**Comment by Robotia** [comment]
@KasperFranz Get rid of tickprofiler, no point with latest server optimizations in `tileentities.yml`.

**Comment by KasperFranz** [comment]
It is related to when someone runs a profile

tileentitites.yml has been there a long time, why is a tickprofiler suddenly bad :)?

**Comment by Robotia** [comment]
@KasperFranz Two reasons: `tileentities.yml` skips tiles when no one is nearby and `spigot.yml` limits max tick-time.

Never profile with tickprofiler, that thing is the bane of KCauldron's existence.
Use WarmRoast, VisualVM, or YourKit

**Comment by KasperFranz** [comment]
The output of VisualVM and tickprofiler is two different things.

I have admins which doesn't have access to the console which uses the output of tickprofiler. 

and how would you go from a VisualVM read there says eg. that net.minecraft.entity.monster.EntitySpider  is using 15% of the total Time (CPU) to know which spider/spiders it is?

**Comment by Robotia** [comment]
@KasperFranz Just `/lagg killmobs` with ClearLag if mobs are taking a lot of time. Tick profiler will not help, I am sorry but just don't use it.

**Comment by Robotia** [comment]
Closing because I can't fix TickProfiler incompatibility, sorry :confused:
