### ISSUE TITLE
Already Decorating Issue Still Present Build 13

### ISSUE THREAD

**Issue by enterprise12nx** [TCPR/KCauldron#53]
*****

**Comment by Robotia** [comment]
@enterprise12nx It wasn't fixed, it was just returned to the way it was.

**Comment by Robotia** [comment]
@enterprise12nx You put your player coords in the log, deleted it just now.

**Comment by enterprise12nx** [comment]
Idc bout my player coordinates, whys it matter :p

**Comment by Robotia** [comment]
@enterprise12nx What if they get raided :confused:

**Comment by enterprise12nx** [comment]
well, none of my players know about this forum, know how to read logs for the most part and require my modpack too.

but ty xD

**Comment by enterprise12nx** [comment]
@Robotia any idea when this will be fixed? 
Its been a dew days and its the only problem we have ran into, servers running amazingly with 100+ mods

**Comment by Cracks777** [comment]
Strange, I dont have this anymore?

**Comment by Robotia** [comment]
@enterprise12nx Sorry it is not my highest priority right now :confused: Working on #55, #22 and #32 are most important right now. The problem occurs because of some mod. You can identify the mod by disabling the world gens one by one in your `cauldron.yml` file and figuring out which one it is.

**Comment by enterprise12nx** [comment]
I understand, is it the mod or is kcauldron causing it to happen?

**Comment by Robotia** [comment]
The mod

**Comment by enterprise12nx** [comment]
@Robotia before i attempt to get help from biomes o plentys issue tracker, do you think enabling
"  load-chunk-on-forge-tick: false" will fix this issue?

This is what is at the end of the log when we do get this crash, ik your busy so just respond when you can, ty!

[04:36:09] [Server thread/INFO] [FML/]: Unknown net.minecraftforge.common.chunkio.QueuedChunk {
 x: 171
 z: 260
 loader: null
 world: world
 dimension: 0
 provider: biomesoplenty.common.world.WorldProviderSurfaceBOP
}
[04:36:09] [Server thread/INFO] [FML/]: This should not happen. Please report this error to Forge.
[04:36:09] [Server thread/INFO] [FML/]: Unknown net.minecraftforge.common.chunkio.QueuedChunk {
 x: 171
 z: 260
 loader: null
 world: world
 dimension: 0
 provider: biomesoplenty.common.world.WorldProviderSurfaceBOP

**Comment by Robotia** [comment]
You could try that, no guarantees though

**Comment by enterprise12nx** [comment]
https://github.com/Glitchfiend/BiomesOPlenty/issues/655#issuecomment-179661048
Biomes o Plenty team, soo much help(sarcastically)

Guess i will have to deal with the problem, or try to fix it myself

**Comment by iKaneki-Ken** [comment]
They are open source.

**Comment by enterprise12nx** [comment]
@iKaneki-Ken yes, but i cannot code :(

**Comment by iKaneki-Ken** [comment]
Ah, gotcha, I'll take a look and see if I can help you. I will not promise anything though.

**Comment by enterprise12nx** [comment]
@iKaneki-Ken any progress?
ive been looking at the logs, and each time it mentions another mod BUT biomes o plenty is always listed with it.
one mentions magic bees, minefactory reloaded, thaumic warden, etc

**Comment by Robotia** [comment]
Already decorating should be basically fixed when B21 (hopefully released tomorrow)

**Comment by Robotia** [comment]
Is out ^

**Comment by enterprise12nx** [comment]
o.o :D

**Comment by Robotia** [comment]
Soon is what I meant, sorry!
