### ISSUE TITLE
INFO Confiscated K20Tuga items for 3 ticks??

### ISSUE THREAD

**Issue by djoveryde** [TCPR/KCauldron#56]
Just checking what this console message means, seems to be spamming console randomly?

INFO Confiscated K20Tuga items for 3 ticks

**Comment by iKaneki-Ken** [comment]
What plugins are you using?

**Comment by djoveryde** [comment]
Lots of plugins, none that confiscates items though, this is a new console message that cropped up after updating to latest unofficial 13 version?

**Comment by iKaneki-Ken** [comment]
That spam isn't being caused by KCauldron as I'm running this version as well and I'm not getting this console spam.

**Comment by djoveryde** [comment]
I'll just ignore it then for now, Might end up finding out what it is but thanks for the confirmation its not kc :)

**Comment by iKaneki-Ken** [comment]
I can tell you for a fact that it is Kai Kikuchi's ForgeRestrictor plugin.

**Comment by Robotia** [comment]
I'm in agreement with kaneki

**Comment by djoveryde** [comment]
@iKaneki-Ken ahh, yes its there. Why does it spam console? Do you know of any way to stop that happening?

**Comment by iKaneki-Ken** [comment]
It's more than likely old debug code that Kai Kikuchi forgot to remove. I suggest you submit an issue about this in his Github repository when you get the chance.

**Comment by djoveryde** [comment]
@iKaneki-Ken Submitted although it actually seems something in his plugin is actually denying the players abilities to open their bags/backpacks or kill mobs without having to look at a block first.

**Comment by iKaneki-Ken** [comment]
It's more than likely air that is preventing it, if it wasn't, it would make the mod completely useless as someone would be able to look straight and fire a really long range projectile that'd be able to break blocks.

**Comment by leelawd** [comment]
@djoveryde I had an issue like that until i reverted the Unofficial KCauldron version to build 12. I'm still not exactly sure what exactly was causing it in build 13 though. So as far as I can tell, its a KCauldron issue and not the plugin.

**Comment by iKaneki-Ken** [comment]
@leelawd Check if you have ForgeRestrictor installed.

**Comment by Robotia** [comment]
Might be related to bukkit double clicks.

**Comment by djoveryde** [comment]
Not sure what the issue is but with forge restrictor literally everything is failing to be usable unless you are looking at a block, so basically the air is defined as a denied block even when opening a backpack. Is this a KC issue that's changed the way regions are checked or definitely Forge restrictor, when removed everything works fine until it's added again

**Comment by djoveryde** [comment]
> Apparently the issue is due to this 

https://github.com/TCPR/KCauldron/commit/9582467ea0ddf80fb7110d5eb6c865ec57c5560c

**Comment by Robotia** [comment]
@djoveryde 
> Might be related to bukkit double clicks.
Is the same thing as https://github.com/TCPR/KCauldron/commit/9582467ea0ddf80fb7110d5eb6c865ec57c5560c

I will be removing other instances of interact() calls in favor of this one for B14.

**Comment by KaiKikuchi** [comment]
For reference, https://github.com/KaiKikuchi/ForgeRestrictor/issues/9

And nope, it's not a debug code: that happens when someone tries to bypass claims/regions protection.

**Comment by Robotia** [comment]
@KaiKikuchi Thanks for the info :smile:  I feel like it would be better off as a debug level log though, not sure they would care, as long as the protection worked.

**Comment by KaiKikuchi** [comment]
Np! Atm the protection doesn't always work! Some modded weapon can be used anyway... like they skip the bukkit's PlayerInteractEvent... so at least server administrators have a player name to blame for griefing.

But I'm working on providing better protection for modded items.

**Comment by Robotia** [comment]
@KaiKikuchi https://github.com/TCPR/KCauldron/commit/9582467ea0ddf80fb7110d5eb6c865ec57c5560c was aimed to prevent mods from even knowing items were activated when the interact event is canceled.
