### ISSUE TITLE
ForgeRestrictor vs KC's new protection?

### ISSUE THREAD

**Issue by djoveryde** [TCPR/KCauldron#58]
I was just wondering with KCauldrons new ability to protect region protected areas from all items is there any valid reason to use ForgeRestrictor Plugin?

**Comment by iKaneki-Ken** [comment]
That's not how it works. It only protects the spawn.

**Comment by Robotia** [comment]
What @iKaneki-Ken said. It only handles a world named "Spawn". I will be implementing the ability to "unrestrict" items in Spawn at some point in the future.
