### ISSUE TITLE
Remove "Moved To Quickly!"

### ISSUE THREAD

**Issue by Time6628** [TCPR/KCauldron#59]
I can no longer move due to this. According to some old bukkit threads this was added to prevent fly and speed hacks without Nocheat plugins. I am currently standing still and this is spamming my console:
```
16:24:53 [Server] INFO [16:24:53 WARN]: TimeTheCat moved too quickly! 0.0,0.0,0.0 (0.7362446254261049, 17.287364536482865, 0.8210849952264293)
16:24:53 [Server] INFO [16:24:53 WARN]: TimeTheCat moved too quickly! 0.0,0.0,0.0 (0.8090600046238042, 17.720167551044256, 0.90229117754165)
16:24:53 [Server] INFO [16:24:53 WARN]: TimeTheCat moved too quickly! 0.0,0.0,0.0 (0.8890769025349831, 18.161803271593087, 0.9915287379535977)
16:24:53 [Server] INFO [16:24:53 WARN]: TimeTheCat moved too quickly! 0.0,0.0,0.0 (0.9770075570460881, 18.61245195725981, 1.0895919883273744)
16:24:53 [Server] INFO [16:24:53 WARN]: TimeTheCat moved too quickly! 0.0,0.0,0.0 (6.162770979767413, 19.08425378642975, 1.9269531527595067)
```

The server is at 20 tps and my ping is 32ms. Also, I do not have anything that changes my speed.

**Comment by iKaneki-Ken** [comment]
Which build of this version of KCauldron are you using? As I'm using B13 and not experiencing this issue.

**Comment by Time6628** [comment]
Latest.

**Comment by iKaneki-Ken** [comment]
When you installed B13, did you start it up with a fresh batch of configs?

**Comment by Robotia** [comment]
@Time6628 do you have `  check-entity-max-speeds: true` instead of false?

**Comment by Time6628** [comment]
It is set to false. @Robotia

**Comment by iKaneki-Ken** [comment]
Set it to true, it'll solve the problem.

**Comment by Robotia** [comment]
Ooh, really?

**Comment by Time6628** [comment]
Didn't fix it.

**Comment by Robotia** [comment]
It is a server-specific problem, I do not have this issue :confused: try a fresh install.

**Comment by Time6628** [comment]
I know it is, I was asking if you could remove it or add an option to disable it if you can. :smile_cat:

**Comment by Bogdan-G** [comment]
such a limitation is in the server code

**Comment by Time6628** [comment]
After much more testing it is caused by bees with the gravity effect. (Spacial, Quantum, and abnormal).

**Comment by Time6628** [comment]
http://ftbwiki.org/Effect

**Comment by Bogdan-G** [comment]
This parameter can be increased if that.
