### ISSUE TITLE
WorldGuard console spam.

### ISSUE THREAD

**Issue by iKaneki-Ken** [TCPR/KCauldron#60]
This version of (K)Cauldron is producing the same spam as depicted in the ticket below:

https://gitlab.prok.pw/KCauldron/KCauldron/issues/257

---

The fix is in the commit below

https://gitlab.prok.pw/KCauldron/KCauldron/commit/6c2be10dc97f3d8234c38525dfe710cc0294e2ca

**Comment by Robotia** [comment]
@iKaneki-Ken Will implement soon.
