### ISSUE TITLE
[Proposal] Name Change

### ISSUE THREAD

**Issue by Yive** [TCPR/KCauldron#63]
Okay so since this repository has gotten a little bit more popular, maybe it's time for a name change instead of being an unofficial fork.

Personally I think Dropper would be nice, but what does everyone else think?

**Comment by iKaneki-Ken** [comment]
Perhaps Meld would suit the project as a name as this is mixing Forge and Spigot together.

**Comment by Shybella** [comment]
This is really embarrassing.

**Comment by Robotia** [comment]
@Shybella Um why?

**Comment by Cracks777** [comment]
Hopper, Its a Hop Skip and a jump between forge and bukkit. lol

**Comment by Cracks777** [comment]
I Do think it needs a name change tho.

**Comment by TerdyTheTerd** [comment]
Not sure if others noticed, on the "official" branch over at gitlab they stated they would ban any users who even mentioned this fork on their issue tracker. Why can't everyone be friends and make one good thing instead of two groups trying to both create the same good thing?

**Comment by Cracks777** [comment]
thats funny, didnt that guy add some of  the changes from here to his?

**Comment by Robotia** [comment]
I feel like there's been some sort of miscommunication, I have never actually had a conversation with Protik, but I think he's unhappy that I created this.

**Comment by Cracks777** [comment]
well, he should be more active to fix bugs instead of adding features that dont help. i mean look at the performance difference between this one and his.

**Comment by Robotia** [comment]
@TerdyTheTerd it's basically me vs whoever made that announcement on GitLab. I really don't think that was Protik.

**Comment by iKaneki-Ken** [comment]
@Robotia Cauldrons code was made public, so nobody can claim ownership of it. So if you want to make and maintain your own, there's nothing anyone can really do.

**Comment by djoveryde** [comment]
Project Magnum - Was the name for a Bottle of mixed wines in the 1700's. Mixed being Bukkit & forge to make the perfect wine :)

**Comment by Robotia** [comment]
@iKaneki-Ken Yeah, I'd like to keep things friendly though. :confused:

**Comment by Robotia** [comment]
Please look at this list of liquid containers for potential names:
https://www.macmillandictionary.com/thesaurus-category/british/containers-for-carrying-or-storing-liquid

**Comment by iKaneki-Ken** [comment]
Out of the list in that link, I like Thermos the most.

**Comment by Robotia** [comment]
@iKaneki-Ken I agree.

**Comment by Robotia** [comment]
Thermos is the new name.
